# Generated by Django 4.2.4 on 2023-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0003_remove_book_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
