# Generated by Django 4.2.4 on 2023-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0004_book_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="writer",
            field=models.CharField(default=" ", max_length=70),
        ),
    ]
