# Generated by Django 4.2.4 on 2023-09-01 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0006_remove_book_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
