# Generated by Django 4.2.4 on 2023-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0007_book_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="budjet",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="writer",
            field=models.CharField(default=1000, max_length=70),
        ),
    ]
