# Generated by Django 4.2.4 on 2023-09-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0008_book_budjet_book_year_alter_book_writer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="writer",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
