# Generated by Django 4.2.4 on 2023-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0014_book_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
