# Generated by Django 4.2.4 on 2023-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0018_alter_book_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="not known", max_length=100)),
                ("last_name", models.CharField(default="not known", max_length=100)),
                ("writer_birthday", models.IntegerField(blank=True, max_length=100)),
            ],
        ),
    ]
