# Generated by Django 4.2.4 on 2023-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0019_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="writer",
            name="writer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
