# Generated by Django 4.2.4 on 2023-09-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0020_writer_writer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_app.writer",
            ),
        ),
        migrations.AlterField(
            model_name="writer",
            name="writer_birthday",
            field=models.IntegerField(blank=True),
        ),
    ]
