# Generated by Django 4.2.4 on 2023-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0021_book_writer_alter_writer_writer_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_best_selling",
            field=models.CharField(default="NO", max_length=100),
        ),
    ]
