# Generated by Django 4.2.4 on 2023-09-09 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0022_alter_book_is_best_selling"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_best_selling",
        ),
    ]
