# Generated by Django 4.2.4 on 2023-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0026_book_is_best_selling"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="not known", max_length=100)),
                ("country", models.CharField(default="USA", max_length=50)),
            ],
        ),
    ]
