# Generated by Django 4.2.4 on 2023-09-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0027_publisherhouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_app.publisherhouse",
            ),
        ),
    ]
