# Generated by Django 4.2.4 on 2023-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0030_writer_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="not known", max_length=100)),
                ("age", models.IntegerField(blank="")),
                (
                    "status",
                    models.CharField(
                        choices=[("main", "Главный"), ("others", "Второстепенный")],
                        default="others",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="characters",
            field=models.ManyToManyField(to="book_app.character"),
        ),
    ]
