# Generated by Django 4.2.4 on 2023-09-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0031_character_book_characters"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
