# Generated by Django 4.2.4 on 2023-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0033_alter_character_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gender",
            field=models.CharField(
                choices=[("man", "Мужчина"), ("woman", "Женщина")],
                default="not known",
                max_length=10,
            ),
        ),
    ]
