# Generated by Django 4.2.4 on 2023-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_app", "0034_character_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("surname", models.CharField(max_length=60)),
                ("feedback", models.TextField()),
                ("rating", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(default="not known", max_length=10),
        ),
    ]
